apiVersion: v1
kind: Pod
metadata:
  name: starassist
  labels: 
    name: starassist-openshift
spec: 
  containers: 
    - image: 172.30.59.28:5000/vidalinux/starassist
      name: starassist
      env:
        - name: STARASSIT_DB_USER
          value: dbuser
        - name: starassist_DB_PASSWORD
          value: dbpass
        - name: starassist_DB_NAME
          value: dbname
        - name: starassist_DB_HOST
          # this is the name of the mysql service fronting the mysql pod in the same namespace
          # expands to mysql.<namespace>.svc.cluster.local  - where <namespace> is the current namespace
          value: mysql
      ports: 
        - containerPort: 80
          name: starassist
      volumeMounts:
        - name: starassist-persistent-storage
          mountPath: /var/www/html
  volumes:
    - name: starassist-persistent-storage
      persistentVolumeClaim:
       claimName: starassist-pvclaim
